# Configuration for the DnsDirector service

# The maximum number of concurrent DNS requests
# to handle. Each active request requires a
# dedicated servicing thread. If the thread
# pool saturates, DnsDirector must wait for
# threads to free up before it can respond.
# Thus it will appear hung momentarily in such
# a case. Going below ~12 has been known to
# cause erratic behavior.
maxConcurrentUdpRequests: 25

# If your network is configured automatically,
# but your DNS servers are configured manually,
# set this option to 'true'. This would be an
# unusual configuration. DnsDirector is unable
# to detect this situation on its own.
dhcpWithStaticDns: false

# Use a widely know set of public DNS servers
# handle all requests not matched in routes.
# Current list is servers from Google and Level 3.
# Only set this to 'true' if you don't want to
# use your system configured DNS servers at all.
usePublicDefaultServers: false

# Provide your own list of DNS server to
# handle all requests not matched in routes.
# Only define this if you don't want to use
# your system configured DNS servers at all.
#defaultServers:
#  - '8.8.8.8'
#  - '8.8.4.4'

# Override the DNS server used by domain suffix.
# Will only match whole parts of the domain suffx,
# e.g. a query for the name 'foobar.example.com'
# does not match a route for 'bar.example.com', but
# it does match a route for 'example.com'.
# Records are matched from most specific to least,
# the order in this file is not relevant.
routes:
  bar.example.com: ['4.2.2.1', '4.2.2.2']
  example.com: ['4.2.2.3', '4.2.2.4']
